# SPDX-FileCopyrightText: Copyright (c) 2022 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: coverage
'on':
  push:
  pull_request:
jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --all-features --ignore-filename-regex 'src/lib\.rs$' --lcov --output-path lcov.info -- --test-threads 1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
          use_oidc: true
